site_name: Children's National BTI Bioinformatics
nav:
  - Home: index.md
  - CNH-Specific Onboarding: cnh-onboarding.md
  - Technology Access Requests: access.md
  - AWS Compute: aws.md
  - CAVATICA Compute: cavatica.md
  - CAVATICA workflow SOP: sop_cwl_cavatica.md
  - Using Docker or Podman: docker.md
  - Using GitHub: github-general.md
  - GitHub Repository Guidelines: github-repo-guide.md
  - GitHub Pull Request Guidelines: github-pr-guide.md
  - Code Review Guidelines: code-review-guide.md
  - Using VSCodium for Code Reviews: vscodium.md
  - Github Tokens: github-tokens.md
  - BTI Project Management: project-mgmt.md
  - Sprint Planning: sprints.md
  - Literature: literature.md
  - Docs: docs-resources.md
theme: readthedocs
